### ISSUE TITLE
Jarvis repo

### ISSUE THREAD

**Issue by primaeval** [Hiltronix/plugin.video.sickrage#9] opened 2017-04-17 08:33 UTC
Hi. Love your addon. Please could you add a Jarvis install for us die-hard Jarvis fans. There is a fundamental problem with Krypton at the moment with HLS streams so I'm sticking with Jarvis.
http://trac.kodi.tv/ticket/17422

I wrote a post about how to support multiple Kodi versions here. The next post is important to.
http://forum.kodi.tv/showthread.php?tid=310315&pid=2556333#pid2556333

Thanks.

**Comment by Hiltronix** [comment] 2017-04-17 16:10
Hi. I'm glad you like the addon.  Unfortunately I'm using some API calls only available in the latest Kodi 17.x.  These functions would be too much work to reproduce in an older version.  That was the reason I switched to supporting only Kodi 17.x.

Please appreciate that I do this on my own time, zero donations, and I actually have no idea how many people are even using the addon.  That being said, I only have time for fixes, and adding new features that I find useful or interesting.  If it were an easy thing to reproduce the functionality, I would do it.  For example, the current version allows the addon to display the video dialogs for shows, and links to actor info details.  This would only be possible in earlier versions of Kodi with creating custom video dialogs and a great deal of work.  Something I was avoiding doing till Kodi 17 came out and made this much easier.  As well as select dialogs with presets, multi-select dialogs with presets, and various other tweaks I don't think were possible before.

I suppose a temp solution would be to use an older version of the addon that works on Jarvis, then turn off "Auto-update" in the addon config.  I know you can turn off Auto-update in Krypton, are you able to in Jarvis?  Hopefully the the Kodi devs will fix the shortcomings you are having issues with so you can move up to 17.x.

If using an older version of the addon is an acceptable solution for now, and you need help finding a zip for that version, let me know.  You could install the older addon version manually using a zip file, and turn off Auto-update.  Sorry if it's not the ideal solution for you at the moment.

**Comment by primaeval** [comment] 2017-04-17 16:27
I'm using your addon in my IMDb Advanced Search addon so I can add Series to Sickrage on a server. It doesn't need any fancy Krypton additions. ;) It's just a one way street. Couchpotato and Trakt are in there too.
http://forum.kodi.tv/showthread.php?tid=267358
This is how your addon gets called.
https://github.com/primaeval/plugin.video.imdb.search/blob/master/main.py#L907

From my long long conversations with the VideoPlayer dev I don't think Krypton is going to get fixed until at least Leia comes out next year. There is so much buck-passing going on with kodi and ffmpeg that no-one wants to take responsibility. I don't know what types of streams they tested with but it is not what the majority of users are using. The HLS delay is a show-stopper once you notice the difference from Jarvis.

I'm not sure if there is an easier way to support multiple repo versions without seperate folders. Maybe it is as simple as adding 2 versions of the same addons.xml to the repo xml file. One with an xbmc.python version of 2.20.0 and one with 2.25.0. Or maybe it is even simpler by leaving the earlier version zip files in the zip folder.

**Comment by Hiltronix** [comment] 2017-04-18 00:56
All the addon zips are online and archived at:
https://github.com/Hiltronix/repo/tree/master/zips/plugin.video.sickrage

The last SR addon before moving it to Krypton was v.2.0.3.  A direct link is:
https://github.com/Hiltronix/repo/raw/master/zips/plugin.video.sickrage/plugin.video.sickrage-2.0.3.zip

Another possible option for you comes to mind.  If your only interest in using the SR addon is to get the series added to the SR server, you could consider adding the functionality directly into your addon.  You could use code I've already written in my addon  You would need to add the SR server settings options to your config, and then instead of calling the SR plugin, you would call code in the sickbeard library script as I do.  It would be a matter of adding config, adding the lookup code to one of your modules, and then adding the sickbeard.py library file from my addon to yours.  If this option interests you I can help you figure that out.  

But if you use other features of the SR addon, then the v.2.0.3 zip, and turning off Auto-update for it, is the best quick solution at the moment.

**Comment by primaeval** [comment] 2017-04-18 05:48
Is there anything different with the protocol from 2.0.3 to now? If it's the same I could just add your 2.0.3 to my repo as a fallback for us Jarvis users. If that is ok with you.

There is quite a bit of code to deal with authentication and folder choosing that I didn't want to have to maintain if possible. If the protocol is stable it might be easier though. 

The tvdb id is easy as I already have an imdb id. I just need to interrogate the directory and quality.

The only other thing is the kodi forum paranoia level. I already had to get my TV Guide Fullscreen addon removed from the banned bin. Has this addon ever been in trouble on the forum? Couchpotato is in the official repo.

**Comment by primaeval** [comment] 2017-04-18 07:09
I've got something working. Would you mind having a look?
I pulled in the AddShow function and the necessary lib files completely.
It should be easier for me to maintain if you change those files at some point. I can just pull them in whole.
I have a branch called sickrage. Here is the commit that pulled everything in.
https://github.com/primaeval/plugin.video.imdb.search/commit/3d48b798590339eaa265c1848341c9053b6e1223

**Comment by Hiltronix** [comment] 2017-04-18 19:46
When you refer to protocol being different from 2.0.3 till now, are you referring to the API in the SickRage server?  If you mean something else, please explain.  As far as the API goes in the current SR server, I have no idea.  There is at least one forked version of SR from what I think of as the original one.  There was a lot of drama when the group of main devs split, and I was asked to pick a side in their drama, and at that point I lost interest in the maintenance and offering my input into either project, I did a private fork and simply maintain my own SR server version for now.  But I've heard no comparability complaints from anyone regarding the API in a while.  I may have updated some code, fixed some potential bugs, and I know I added one function to the addon API library, sickbeard.py.  But all in all there were no API specific changes.

Be aware that there are some API differences between a SickRage and SickBeard server.  If you are only interested in supporting SR, then make sure you default __servertype__ to 'SickRage', which should be the default I've set.

FYI, The newer versions of the addshow.py module has changed to include calls specific to Kodi 17 API.  So you aren't likely going to want to pull newer versions of that file.  And only if there was an SR API change, would you need to consider pulling a newer version of sickbeard.py.

I have no issue with you keeping a specific SR addon version in your repo.

I tried once to get the SR Addon added to the official Kodi repo, with no success.  Unless something has improved, it was a sad and manual process of emailing a distribution list a text formatted template, and then having to check the email dist list for feedback or acceptance.  I lost interest and gave up on this process, so that's as far as I got with seeing if it would be accepted officially.  As for the Kodi forums, I've made little effort to promote the addon there.  Quite honestly I have limited patience then it comes to forums and a certain percentage of opinionated people that lurk in every forum.  The addons I write I do for myself, I share on my repo for those interested, and promote them little.  So currently I've had little negative feedback.

I briefly reviewed the commit page.  Is there a typo here on this line?
+@plugin.route('/aickrage_addshow/<title>')
Was it meant to be:
+@plugin.route('/sickrage_addshow/<title>')

To solve the issue and concern you explained you have with Krypton, I think the route you are taking to incorporate the code you need into your addon makes the most sense for now.  Have you tested your code with these additions yet?

**Comment by primaeval** [comment] 2017-04-18 20:18
Thanks for that.

Luckily the typo didn't affect how I was calling the addshow function and it does work ok on Jarvis for my SickRage server. Well spotted.

As long as the API calls to AddShow remain the same everything should be ok for a while but you never know. There is always one meddling noobie just out of school who thinks he knows better than all the devs that have been doing it for decades. There is a massive forum thread with people complaining that the new version of the IMDb Advanced Search page broke almost everything that people were relying on. I had to rewrite a lot of the addon to deal with it.

I'm using the forked SickRage since the original started to frequently stop working when the owner went awol and all the drama started.

I know what you mean about submitting addons. Apart from the iplayerwww addon that I helped develop I just keep all my addons in my own Github repos too. It is nice to be able to get a bug report from a user and get a new version out within an hour or two. It can take weeks with official addons.

To find out how many people have installed my addons I usually do a little oneshot request for a file at goo.gl with some extra info in the referrer attribute. It appears in the analytics page. eg
https://github.com/primaeval/script.tvguide.fullscreen/blob/master/service.py#L74

**Comment by Hiltronix** [comment] 2017-04-19 14:46
Glad you got it working.  

I wasn't happy with the work being done on the SR project near the end before the split.  And the attitude of one dev in particular was not longer tolerable to me.  And I also had limited luck with the original SR project when the project owner took it back.  As I result, I froze a version I found usable, tweaked it for my needs.  I'm now slowly developing a replacement solution of my own.  The SR addon will eventually evolve to be the front end for that.  At some point I will have to fork it, so that those who want to continue using it for SR still have it, and won't be confused by whatever I add for my new solution.

I can only imagine that the Kodi team intentionally make it difficult and awkward to submit addons to keep most addon developers at a distance.  The process for submitting addons is similar to registering a domain name in the very earliest days of the Internet.  No one would leave the process that way without specific reason.  

Thanks for the tip on tracking the downloads.  I know I should have done something like that already, but never got around to it yet. :)

**Closed as completed** 2018-04-14 00:17 UTC
